GET http://localhost:3000/orders

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "amount": 150
}

### 
GET http://localhost:3000/orders/9c7835bc-e8ea-4f07-9355-dc85702b1166

### 
GET http://localhost:3000/orders/invalid-id

###
PATCH  http://localhost:3000/orders/9c7835bc-e8ea-4f07-9355-dc85702b1166
Content-Type: application/json

{
  "amount": 53.90
}

###
DELETE http://localhost:3000/orders/d75ffe0a-1e32-4d45-8af3-2046954202c8